SELECT TOP (1000) [ID],
      [SERVER],
      [ODEE_VERSION],
      [LINES],
      [CLEAN],
      [RECORDS],
      [ERRORS],
      [WARNS],
      [INFOS],
      [SPRING_TIMERS],
      [START],
      [END],
      [MIN],
      [MAX],
      [SUM],
      [AVERAGE],
      [MEDIAN],
      [SATISFIED],
      [TOLERANT]
  FROM [DEV].[dbo].[EXECUTIONS]